version: "3.9"

services:

  redis:
    image: redis:6.2

  worker:
    build: .
    command: python -m distribute_challenge.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always

  dashboard:
    build: .
    command: rq-dashboard
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
     - "9181:9181"

  client:
    build: .
    command: python -m client.main
    environment:
      - REDIS_HOST=redis
    profiles:
      - client
    volumes:
      - .:/app
    depends_on:
      - redis

  test:
    build: .
    command: python -m pytest tests
    environment:
      - ENV=test
    profiles:
      - test
    volumes:
      - .:/app
